import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go

# ---------------------------------------------------------
# 1. ตั้งค่าหน้าเว็บ
# ---------------------------------------------------------
st.set_page_config(
    page_title="My AI Portfolio Tracker",
    page_icon="🚀",
    layout="wide"
)

st.title("🚀 My Grand Portfolio Tracker")
st.markdown("ติดตามความเคลื่อนไหวของ **AMZN, V, NVDA, LLY, WBD, TSM** แบบ Real-time")
st.markdown("---")

# ---------------------------------------------------------
# 2. รายชื่อหุ้นในพอร์ตของคุณ (แก้ไขเพิ่มลดตรงนี้ได้)
# ---------------------------------------------------------
my_stocks = ['AMZN', 'V', 'NVDA', 'LLY', 'WBD', 'TSM']

# ---------------------------------------------------------
# 3. ฟังก์ชันดึงข้อมูล (Cache เพื่อให้โหลดเร็ว)
# ---------------------------------------------------------
@st.cache_data
def get_stock_data(tickers):
    data = {}
    for symbol in tickers:
        stock = yf.Ticker(symbol)
        # ดึงประวัติย้อนหลัง 6 เดือน
        hist = stock.history(period="6mo")
        # ดึงข้อมูลบริษัท
        info = stock.info
        data[symbol] = {
            'history': hist,
            'current_price': info.get('currentPrice', hist['Close'].iloc[-1]),
            'prev_close': info.get('previousClose', hist['Close'].iloc[-2]),
            'name': info.get('shortName', symbol)
        }
    return data

# โหลดข้อมูล (อาจใช้เวลา 2-3 วินาที)
with st.spinner('กำลังดึงข้อมูลตลาดล่าสุด...'):
    stock_data = get_stock_data(my_stocks)

# ---------------------------------------------------------
# 4. แสดงผลเป็น Card สวยๆ ด้านบน
# ---------------------------------------------------------
cols = st.columns(len(my_stocks)) # แบ่งคอลัมน์เท่าจำนวนหุ้น

for i, symbol in enumerate(my_stocks):
    info = stock_data[symbol]
    price = info['current_price']
    prev = info['prev_close']
    change = price - prev
    pct_change = (change / prev) * 100
    
    # กำหนดสี (เขียว=ขึ้น, แดง=ลง)
    color = "green" if change >= 0 else "red"
    
    with cols[i]:
        st.metric(
            label=symbol,
            value=f"${price:.2f}",
            delta=f"{pct_change:.2f}%"
        )

st.markdown("---")

# ---------------------------------------------------------
# 5. กราฟราคาเชิงลึก
# ---------------------------------------------------------
st.subheader("📈 Price Trend Analysis")

# เลือกหุ้นที่จะดูกราฟ
selected_stock = st.selectbox("เลือกหุ้นเพื่อดูกราฟละเอียด:", my_stocks)

if selected_stock:
    df = stock_data[selected_stock]['history']
    
    # สร้างกราฟด้วย Plotly
    fig = go.Figure()
    
    # เส้นราคาปิด
    fig.add_trace(go.Scatter(
        x=df.index, 
        y=df['Close'], 
        mode='lines', 
        name='Close Price',
        line=dict(color='#00C9FF', width=2)
    ))
    
    fig.update_layout(
        title=f"กราฟราคา {selected_stock} (ย้อนหลัง 6 เดือน)",
        xaxis_title="Date",
        yaxis_title="Price (USD)",
        template="plotly_dark",
        height=500
    )
    
    st.plotly_chart(fig, use_container_width=True)

# ---------------------------------------------------------
# 6. ส่วนท้าย (Footer)
# ---------------------------------------------------------
st.markdown("---")
st.caption("Auto-generated by Gemini Assistant | Data source: Yahoo Finance")